services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_halofiles_app
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "127.0.0.1:10800:8000"
    volumes:
      - logs_volume:/app/logs
    networks:
      - halo_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  halo_network:
    driver: bridge

volumes:
  logs_volume:
